spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  youtube-stream-key: stream-key
  audio-file-name: "audio.mp3"
  video-library: "/data/videos"
  cache-directory: "/data/cache"
  intro-file-name: "intro-new.mp4"
  outro-file-name: "outro-new.mp4"
  audio-prelude-duration: 7.8
  segment-length: 10
  outro-offset: -6
  wait-between-streams: 10


management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "prometheus"

