spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  minio:
    url: http://localhost:9000
    bucket: main
    create-bucket: true
    access-key: minioadmin
    secret-key: minioadmin

application:
  video-url-prefix: "https://video.singing4peace.de/"
  audio-file-path: "/data/audio.mp3"


management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "prometheus"

