spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  minio:
    url: http://localhost:9000
    bucket: main
    create-bucket: true
    access-key: minioadmin
    secret-key: minioadmin

application:
  youtube-stream-key: stream-key
  audio-file-path: "/data/audio.mp3"
  video-library: "/data/videos"
  cache-directory: "/data/cache"
  intro-file-name: "intro.mp4"
  outro-file-name: "outro.mp4"
  segment-length: 10
  silence-before: 5
  silence-after: 5


management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "prometheus"

